# Not Change
chain:
  # Not Change
  endpoint: "grpc-testnet.prover.xyz:80"
  # Not Change
  chain_id: "cysicmint_9001-1"
  # Not Change
  gas_coin: "CYS"
  # Not Change
  gas_price: 10
  # Modify Hereï¼š! Your Address (EVM) submitted to claim rewards
claim_reward_address: __EVM_ADDRESS__

server:
  # don't modify this
  cysic_endpoint: "https://ws-pre.prover.xyz"
